### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by ksanty** [atsign-company/events#10]
[Devpost Registration Page](https://fhirathack.devpost.com/)
Can we do a special FHIR Promo for @signs like we did with flutter vikings? Launch July 9 - 11

- [x] Identify Keynote / Midnote - [Sean Riddell](https://www.digitalhealth.net/2013/04/ehi-interview-sean-riddell/) [Mary Goldstein](https://biox.stanford.edu/people/mary-goldstein)
- [x] Social media outreach (Twitter, LinkedIn)
- [ ] Day in the life of video?
- [x] FHIR DevDays
- [x] Informatics Slack Channels
- [x] Landing page Creation
- [x] Sign ups @aannttoo targeted 50 teams?
- [x] Continue outreach (Colin posted on LinkedIn)

**Comment by hakeemawbrey** [comment]
[Fhir @hack logo options.pdf](https://github.com/atsign-company/events/files/6610317/Fhir.%40hack.logo.options.pdf)

Made some potential logos for the hackathon. All copy (text) is TBD.

I would love feedback, so we can start making all the other marketing materials for promotion of the event.

**Comment by ksanty** [comment]
> [Fhir @hack logo options.pdf](https://github.com/atsign-company/events/files/6610317/Fhir.%40hack.logo.options.pdf)
> 
> Made some potential logos for the hackathon. All copy (text) is TBD.
> 
> I would love feedback, so we can start making all the other marketing materials for promotion of the event.

Hi @hakeemawbrey can you number the graphics, so people can point out accordingly?  Thank you!!
