### ISSUE TITLE
Fun and Games during Hackathon

### ISSUE THREAD

**Issue by ksanty** [atsign-company/events#13]
- [ ] Minecraft server 
- [ ] List of games included on the [schedule](https://docs.google.com/spreadsheets/d/1gz2ysOKSSZJFQuHtDPKQ1su9iNmkL7LmTnueyEd8CVw/edit#gid=1093082634)
- [ ] Visual engagement, photo opp, [virtual photo booth](https://github.com/flutter/photobooth)?  Look for one.  @hakeemawbrey @tinashe404 
- [ ] [Photo booth article](https://medium.com/flutter/how-its-made-i-o-photo-booth-3b8355d35883)

Esthers Song (Hakeem has MP3 File)
Open up card for full list

**Comment by tinashe404** [comment]
**PC**
Codenames
https://codenames.game/

Slither
http://slither.io/ 
https://sites.google.com/site/slitherioprivate/ 

JackBox Games
https://www.jackboxgames.com/

Skribbl
https://skribbl.io/

Scattergories
https://scattergoriesonline.net/new-game.xhtml

A Whole lot of card games
https://playingcards.io/

Tetris
https://jstris.jezevec10.com/

**Mobile**
Psych!
https://www.warnerbros.com/games-and-apps/psych-outwit-your-friends

**Comment by hakeemawbrey** [comment]
Keyboard racer
https://play.typeracer.com?rt=o70jj6e2t
Up to 200 people

**Comment by tinashe404** [comment]
Uno (4 players)
https://www.crazygames.com/game/uno-online

Just fall (multiplayer)
https://www.crazygames.com/game/justfall-lol

Super Hex (multiplayer)
https://www.crazygames.com/game/superhexio
