### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by ksanty** [atsign-company/events#2]
Communication platforms (Discord, video platform)

Video and collab tool - need a assessment of tools (costs, benefits, gaps)

- [x] https://www.airmeet.com/ (if we have 100ppl its free - $200 over 100)
- [x] Need an Airmeet briefing from @FireJuun 
- [ ] Discord channels - Yaswanth
- [x] [Pricing Doc](https://docs.google.com/document/d/1HNnZymHGngwDoetne-uRqNpIU6XWwO2woru3qt63CfE/edit)

Submissions

- [x] https://devpost.com/

[Judging/scoring submission](https://docs.google.com/presentation/d/1J-ezA6MLKifwQaQN6oDm97q1glgw-L67fHEZy5ZFga0/edit#slide=id.ge1f9ce2d93_0_22)

- [x] TBD (can be done on the backend of Airmeet)
- [x] Google Form
- [x] Devpost

Development Platform
- [x] None Prescribed
- [x] Could we still encourage the use of Flutter, FHIR and the @platform through the use of extra scoring points - [scoring rubric](https://docs.google.com/presentation/d/1J-ezA6MLKifwQaQN6oDm97q1glgw-L67fHEZy5ZFga0/edit#slide=id.ge1f9ce2d93_0_22)

**Comment by TylerTrott** [comment]
Doc on the different communication platforms -> https://docs.google.com/document/d/1HNnZymHGngwDoetne-uRqNpIU6XWwO2woru3qt63CfE/edit?usp=sharing

**Comment by cconstab** [comment]
As the event is done, closing issue.. iF you need it open again just say..
