### ISSUE TITLE
Schedule for the 3 days

### ISSUE THREAD

**Issue by ksanty** [atsign-company/events#20]
How do we breakdown the 3 days @atsigndenise  has existing templates to pull from.

- [x] Publish on DevPost
- [x] Finalize games
- [x] Add announcements and timing
- [x] [Schedule Framework](https://docs.google.com/spreadsheets/d/1XycZN5W3UysKvwlXtWmKScQbNHcWoseTENKAp5NgQgo/edit#gid=0)

Should we give people a break (optional, but we're going to have coverage)

[SB Hacks schedule](https://docs.google.com/spreadsheets/d/1hYfi1aovIPGV6Ia2KWFQ_jfFubNRnGMgm8BIMrjbwBg/edit#gid=0)

**Comment by aannttoo** [comment]
https://docs.google.com/spreadsheets/d/1XycZN5W3UysKvwlXtWmKScQbNHcWoseTENKAp5NgQgo/edit?usp=sharing
