### ISSUE TITLE
Press Release announcing event and exciting details

### ISSUE THREAD

**Issue by ksanty** [atsign-company/events#21]
- [x] Content passed to @jenmonroe 
- [x] Second draft (funding PR )by next week
- [x] Barbara sign off on funding release
- [x] Funding release to go live week of 6/28
- [x] FHIR hacks info to PR firm
- [x] Barbara FHIR hacks quote to PR firm
- [x] FHIR hacks press release draft
- [x] FHIR hacks release launch week of 6/28

**Comment by jenmonroe** [comment]
Reached out to PR rep Sarah Fraser via email to get press release started. 6/24
