### ISSUE TITLE
Mentors for the various tracks

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-company/events#23]
- [x] Zariot +3-4
    - [ ] Subset of DevOp team (Marko, Tommi, Jerry) + Jimmy (TBC)
- [x] Chris Swan
- [x] Dean Rea
- [x] Kevin Nickels
- [x] Colin Constable
- [x] Venkat

**Comment by ksanty** [comment]
Hi all, please be sure to update progress before tomorrow's sprint call. TY!

**Comment by anthonyvprakash** [comment]
@anthonyvprakash  to update live site as ZARIOT team
