### ISSUE TITLE
Plan for the 3-days and publish

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-company/events#24]
- [x] Overall structure and flow for the 3 days
- [x] Key note timing / info sessions / practice pitch etc
- [ ] Prep and notifications

https://calendar.google.com/calendar/u/0?cid=Y19pcGsydGEzdjdmN3ZlbGRmbmhwb2lxamRia0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by ksanty** [comment]
#29 replaces
