### ISSUE TITLE
Judging Panel for the tracks

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-company/events#28]
- [x] ZARIOT +1
    - [x] Still investigating options (John OConnell, Explayo Group)
- [x] Simon Lightfoot
- [x] Randy Fortier
- [x] Gen Ashley
- [x] Sujith Nair
- [x] Correy Voo
- [x] Venkat
    - [x] @ksanty has a long list, but want to speak with Anthony to see who he wants 
    - [x] Outreach to Jon Callas @atsigndenise

**Comment by XavierChanth** [comment]
I haven't reached out to Randy since I last spoke to him, we can speak to him again when we meet with the rest of the judges.

**Comment by hakeemawbrey** [comment]
Will make a promo graphic for all the judges
