### ISSUE TITLE
Finalize Tracks and Sponsors

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-company/events#31]
- [x] Product Space
- [x] Outreach to LinQuest CTO for sponsorship, waiting to hear back
- [x] Zariot confirmed as sponsor

- [x] beckn will be part of the ecommerce track

**Comment by ksanty** [comment]
Hi all, please be sure to update progress before tomorrow's sprint call. TY!

**Comment by anthonyvprakash** [comment]
Moving forward with our current format
