### ISSUE TITLE
Princeton Hack - @ Company Career Panel, Nov. 6, 10:00 to 11:00 am, pacific

### ISSUE THREAD

**Issue by atsigndenise** [atsign-company/events#39]
We have been offered the opportunity to host a career panel.  Students at Hack Princeton are most interested in how to become a CEO or CTO and what a CEO or CTO day is like.  It might also be interesting to run a panel on leading in a Flat vs Hierarchical Organization. This is an optional panel, but it might be an opportunity for us to develop thought leadership. The Hack Princeton students like the idea of a GenZ moderating the panel.

- [x] Moderator of career panel determined -- will be Alison Lee of Hack Princeton @atsigndenise 
- [x] 2-4 start up CEOs or CTOs confirmed (Barbara and Kevin) and (Colin and Chris) @atsigndenise @tallent @nickelskevin @cconstab @cpswan 
- [x] Dry run organized with questions ahead of time @atsigndenise Alison Lee
- [ ] Prep @atsigndenise 
- [ ] Hold dry-run @atsigndenise 
- [ ] Delivery @cpswan @cconstab @nickelskevin @tallent

**Comment by nickelskevin** [comment]
Event completed - closing this issue.
